package app;

/**
* app/chatHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from app.idl
* dimanche 19 novembre 2017 13 h 01 CET
*/

public final class chatHolder implements org.omg.CORBA.portable.Streamable
{
  public app.chat value = null;

  public chatHolder ()
  {
  }

  public chatHolder (app.chat initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = app.chatHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    app.chatHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return app.chatHelper.type ();
  }

}
