package app;


/**
* app/talkOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from app.idl
* dimanche 19 novembre 2017 13 h 01 CET
*/

public interface talkOperations 
{
  void printMessage (String message);
} // interface talkOperations
